# Generated by Django 6.0.6 on 2026-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('uploaded_image', models.ImageField(upload_to='uploads/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('plate_crop', models.ImageField(blank=True, null=True, upload_to='plate_crops/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
